export enum ActivityHistoryEnums {
  signUp = 'SignUp',
  login = 'Login',
  updateProfile = 'Update Profile',
  updateProfilePicture = 'Profile Picture',
  riskAnalysis = 'Risk Analysis',
  retirementAccount = 'Retirement Account',
  accountAnalysis = 'Account Analysis',
  subscriptionChanges = 'Subscription Changes',
  correspondence = 'Correspondence',
  emailId = 'Email',
  address = 'Address',
  firstName = 'First Name',
  lastName = 'Last Name',
  Phone = 'Phone',
  ageOrRetirementAge = 'Age or Retirement age',
}

export enum ActivityHistoryEventTypeEnums {
  signup = 'Registered Successfully',
  updatedRiskLevelScore = 'Risk score updated',
  UpdatedRetirementAccount = 'Total retirement account updated',
  updatedProductPlan = ' Subscription Plan updated',
  subscriptionSuccess = 'Payment Success',
  subscriptionFailure = 'Payment Failure',
  couponCode = 'Coupon code applied',
  loggedIn = 'LoggedIn',
  logOut = 'LogOut',
  updateProfilePicture = 'Profile picture updated',
  updatedUserProfile = 'User profile Updated',
  deletedUserProfilePicture = 'Profile Picture deleted',
  changePassword = 'Left Lane Reset Password',
  updateAgeAndRetirementAge = 'Age or Retirement age updated',
  modifiyEmail = 'Email id modified',
  updateEmail = 'Email id Updated',
  emailVerificationLink = 'Email verification link',
  forgotPasswordVerificationCode = 'Reset Password verification code',
  address = 'Address updated',
  firstName = 'First name updated',
  lastName = 'Last name updated',
  Phone = 'Mobile Number updated',
}
